### ISSUE TITLE
Setting DEBUG=0 causes issues

### ISSUE THREAD

**Issue by dfbravo** [firmadyne/libnvram#2]
Setting the `DEBUG` macro in `config.h` causes a kernel panic - init not syncing. I think the issues is that functions `nvram_set_default_builtin()`, `nvram_set_default_table(a)`, and `foreach_nvram_from(...)` to are not executing. See function `nvram_set_default() - Line 571`.

I wanted to reduce the print messages from libnvram, so I commented out all PRINT_MSG calls except for those that include a function call in the parameters, including those I mentioned above, and the kernel panic did not occur.

**Comment by ddcc** [comment]
Sorry for the delay, I've been traveling. I believe this is fixed in #3 .
