### ISSUE TITLE
Macro Definition

### ISSUE THREAD

**Issue by xyzmpv** [firmadyne/libnvram#6]
I am reading the code of nvram.c.However,this macro definition confuses me.(Though I have read [the link](https://lkml.org/lkml/2007/3/9/10) in source code) 
The macro definition is below:
`#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + sizeof(typeof(int[1 - 2 * !!__builtin_types_compatible_p(typeof(arr), typeof(&arr[0]))])) * 0)`

Why the end of macro definition appears `*0`?

**Comment by ddcc** [comment]
https://lkml.org/lkml/2007/3/10/127

**Comment by xyzmpv** [comment]
> 

Thanks for developer's reply. Happy Luna new year:）
